# build config options

#==========================================================
#  misc config (these end up overriding cli params I think)
#==========================================================
### (CROSS) target arch: default, x86, x86_64, arm, aarch64
#TARGET_ARCH=
### make flags, you may leave this blank or add -j2 -j4 etc
MKFLG=
### yes/no, _strip() in ./func will not strip binaries if this is no
ALLOW_STRIP_BIN=yes
### produce static binaries (including libc)? [yes|no] [default:yes]
### (you can use -static or -shared cli params instead)
#STATIC_LINK=yes
### run tests after compiling? [yes|no] [default:no]
### (linux-only) [not all pkgs support this] (you can use -check param instead)
#WCROSS_MAKE_CHECK=yes
# chroot
ALPINE_LINUX_VER=3.15.6
ALPINE_LINUX_VER=3.16.3
ALPINE_LINUX_VER=3.17.0
ALPINE_LINUX_SITE=https://dl-cdn.alpinelinux.org/alpine


#====================================================
#          apps/pgks to compile automatically
#====================================================
#PACKAGES='
#busybox
#cryptsetup
#dialog
#dosfstools
#e2fsprogs
#f2fs-tools
#exfat-utils fuse-exfat
#mp
#ntfs-3g
#'
