#!/bin/sh
# special script that is called if `-pkg local`

export W_00_LOCAL_BUILD='yes'

if [ -z "$MWD" ] || [ -z "$XPATH" ] ; then
    echo "ERROR: \$MWD has not been set"
    exit 1
fi
. ${MWD}/func || exit 1

# ====================================================

if [ -z "$ORIG_DIR" ] ; then
    exit_error "\$ORIG_DIR has not been set"
fi

if [ -d /WBUILDS ] ; then
    # this is a chroot, must fix ORIG_DIR set by wmake_static_musl
    ORIG_DIR=$(echo $ORIG_DIR | sed "s%${MWD_ORIG}%${MWD}%")
fi
cd $ORIG_DIR

echo -- $ORIG_DIR

# ====================================================
# ./configure

if [ -f configure.ac ] || [ -f configure ] ; then
    . ${MWD}/func
    if [ -f configure ] && [ ! -d /WBUILDS ] ; then
        if [ ! -f configure.ac ] && [ ! -f configure.project ] ; then
            # not autotools or wconf add more stuff
            CC_OPT="$CROSS_MK_PARAMS CFLAGS=--sysroot=${TOOLCHAIN_ROOT} CXXFLAGS=--sysroot=${TOOLCHAIN_ROOT}"
        fi
        opts="${CC_OPT}"
    fi
    _configure ${WCONF_PARAMS} #extra opts
    #WMAKE='bmake'
    _make ${WMAKE_PARAMS}
    #_make strip
    exit $?
fi


# ====================================================
# CMake
if [ -f CMakeLists.txt ] ; then
    _cmake || exit
    _make
    exit $?
fi


# ====================================================
# meson
if [ -f meson.build ] ; then
    _meson_build
    exit $?
fi


# ====================================================
# Makefile

Makefile=''
if [ -f Makefile ] ; then
    Makefile='Makefile'
elif [ -f makefile ] ; then
    Makefile='makefile'
else
    echo "ERROR: missing Makefile / configure / configure.ac"
    exit 1
fi

# detect mk-configure project
if test -n "${Makefile}" && grep '\.include <mkc.' ${Makefile} ; then
    . ${MWD}/func
    _mk_configure
    exit $?
# detect bmake Makefile
elif test -n "${Makefile}" && grep '\.include <' ${Makefile} ; then
    . ${MWD}/func
    WMAKE=bmake _make
    exit $?
fi

